services:
    listing:
        class: PawelLen\DataTablesListing\ListingFactory
        arguments:
            formFactory: "@form.factory"
            registry: "@doctrine"
            eventDispatcher: "@event_dispatcher"
            renderer: "@listing.renderer"

    listing.renderer:
        class: PawelLen\DataTablesListing\Renderer\ListingRenderer
        arguments:
            router: "@router"
            defaultTemplate: "%data_tables_listing.default_template%"
            assetsConfiguration: "%data_tables_listing.include_assets%"
            environment: "@twig"

    listing.not_initialized_renderer:
        class: PawelLen\DataTablesListing\Renderer\ListingRenderer
        arguments:
            router: "@router"
            defaultTemplate: "%data_tables_listing.default_template%"
            assetsConfiguration: "%data_tables_listing.include_assets%"

    listing.extension:
        class: PawelLen\DataTablesListing\Twig\ListingExtension
        arguments:
            renderer: "@listing.not_initialized_renderer"
        tags:
            - { name: twig.extension }

    listing.ajax_authentication_listener:
        class: PawelLen\DataTablesListing\EventListener\AjaxAuthenticationListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 999 }
